/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppComplaintsIndexRouteImport } from './routes/_app/complaints/index'
import { Route as AppComplaintsHistoryRouteImport } from './routes/_app/complaints/history'
import { Route as AppComplaintsNewRouteImport } from './routes/_app/complaints/new'
import { Route as AppWarrantyIndexRouteImport } from './routes/_app/warranty/index'
import { Route as AppWarrantyNewRouteImport } from './routes/_app/warranty/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsIndexRoute = AppComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsHistoryRoute = AppComplaintsHistoryRouteImport.update({
  id: '/complaints/history',
  path: '/complaints/history',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsNewRoute = AppComplaintsNewRouteImport.update({
  id: '/complaints/new',
  path: '/complaints/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWarrantyIndexRoute = AppWarrantyIndexRouteImport.update({
  id: '/warranty/',
  path: '/warranty/',
  getParentRoute: () => AppRoute,
} as any)
const AppWarrantyNewRoute = AppWarrantyNewRouteImport.update({
  id: '/warranty/new',
  path: '/warranty/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/complaints/history': typeof AppComplaintsHistoryRoute
  '/complaints/new': typeof AppComplaintsNewRoute
  '/warranty/new': typeof AppWarrantyNewRoute
  '/complaints/': typeof AppComplaintsIndexRoute
  '/warranty/': typeof AppWarrantyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/complaints/history': typeof AppComplaintsHistoryRoute
  '/complaints/new': typeof AppComplaintsNewRoute
  '/warranty/new': typeof AppWarrantyNewRoute
  '/complaints': typeof AppComplaintsIndexRoute
  '/warranty': typeof AppWarrantyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/complaints/history': typeof AppComplaintsHistoryRoute
  '/_app/complaints/new': typeof AppComplaintsNewRoute
  '/_app/warranty/new': typeof AppWarrantyNewRoute
  '/_app/complaints/': typeof AppComplaintsIndexRoute
  '/_app/warranty/': typeof AppWarrantyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/complaints/history'
    | '/complaints/new'
    | '/warranty/new'
    | '/complaints/'
    | '/warranty/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/complaints/history'
    | '/complaints/new'
    | '/warranty/new'
    | '/complaints'
    | '/warranty'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/complaints/history'
    | '/_app/complaints/new'
    | '/_app/warranty/new'
    | '/_app/complaints/'
    | '/_app/warranty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/': {
      id: '/_app/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AppComplaintsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/history': {
      id: '/_app/complaints/history'
      path: '/complaints/history'
      fullPath: '/complaints/history'
      preLoaderRoute: typeof AppComplaintsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/new': {
      id: '/_app/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof AppComplaintsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warranty/': {
      id: '/_app/warranty/'
      path: '/warranty'
      fullPath: '/warranty/'
      preLoaderRoute: typeof AppWarrantyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warranty/new': {
      id: '/_app/warranty/new'
      path: '/warranty/new'
      fullPath: '/warranty/new'
      preLoaderRoute: typeof AppWarrantyNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppComplaintsHistoryRoute: typeof AppComplaintsHistoryRoute
  AppComplaintsNewRoute: typeof AppComplaintsNewRoute
  AppWarrantyNewRoute: typeof AppWarrantyNewRoute
  AppComplaintsIndexRoute: typeof AppComplaintsIndexRoute
  AppWarrantyIndexRoute: typeof AppWarrantyIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppComplaintsHistoryRoute: AppComplaintsHistoryRoute,
  AppComplaintsNewRoute: AppComplaintsNewRoute,
  AppWarrantyNewRoute: AppWarrantyNewRoute,
  AppComplaintsIndexRoute: AppComplaintsIndexRoute,
  AppWarrantyIndexRoute: AppWarrantyIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
